---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: "kirillshtrykov/debian-ansible:12.8"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
